# -*- coding: utf-8 -*-
"""22Sep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kebcwgiufk0821NsNSdYQ4b22OhqQaGe
"""

# !pip install spacy

# import spacy

#nlp = spacy.blank("en")

# doc = nlp("my gmail id is kiran@gmail.com and i am 5km away")

# tokens = [token.text for token in doc]
# print(tokens)

import sklearn
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

df=pd.read_csv("twitter_training.csv")

df.columns

df=df.drop(["2401","Borderlands"],axis=1)

df.columns

df=df.rename(columns={"im getting on borderlands and i will murder you all ,":"text"})
df=df.rename(columns={"Positive":"sentiment"})

df.columns

df.info()

df.dropna(thresh=2,inplace=True)

df.info()

df["sentiment"].value_counts()

df["text"]=df["text"].apply(lambda x : word_tokenize(x))

print(df.text[1])

from nltk.corpus import stopwords
nltk.download("stopwords")

def lower(text):
  return [word.lower() for word in text]
df["text"]=df["text"].apply(lower)

df["text"]=df["text"].apply(lambda x:[word.lower() for word in x ])

df.head()

words=stopwords.words("english")

def stop(text):
  return [word for word in text if word not in words]
df["text"]=df["text"].apply(stop)

df["text"].head()

from sklearn.feature_extraction.text import CountVectorizer

df["text"]=df["text"].apply(lambda x : " ".join(x)  )

vec=CountVectorizer(ngram_range=(1,2))

from nltk.stem import PorterStemmer

stem=PorterStemmer()

df["text"]=df["text"].apply(lambda x : [stem.stem(y) for y in x.split()])

df["text"]=df["text"].apply(lambda x : " ".join(x))

df["text"]

x=vec.fit_transform(df["text"])

print(x.shape)

# print(x)

# vec.get_feature_names_out()
# print(vec.get_feature_names_out())

from sklearn.preprocessing import LabelEncoder
en=LabelEncoder()
df["sentiment"]=en.fit_transform(df["sentiment"])

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

model.fit(x,df['sentiment'])

import joblib
joblib.dump(model,"model.pkl")
joblib.dump(vec,"vec.pkl")
joblib.dump(en,"en.pkl")



def fun(test):
  new=[]
  for word in test:
    new.append(stem.stem(word))
  return " ".join(new)
test=input("enter your review (quit to exit)")
while(test.lower()!="quit"):
  test=test.lower()
  test=test.split(" ")
  test=[word for word in test if word not in words]
  test=fun(test)
  # test="accept"
  test=vec.transform([test])
  # test=" ".join(test)
  pre=model.predict(test)
  print(pre[0])
  print("The review is ",(en.inverse_transform([pre[0]])[0]))
  test=input("enter your review (quit to exit)")

# test



# test



# print(test.toarray())











# test = ["This product is amazing"]

# test_vector = vec.transform(test)
# print(test_vector.toarray())
# #